sonar.projectKey=khw315_speedrr
sonar.organization=khw315
sonar.sourceEncoding=UTF-8

# Go Coverage & Test Configuration
sonar.go.coverage.reportPaths=coverage.out,sidecars/youtube-monitor/coverage.out
sonar.sources=.
sonar.exclusions=main.go,sidecars/youtube-monitor/main.go,**/*_test.go,**/vendor/**,logs/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
